In [56]:
import pandas as pd 
data = pd.read_csv(r'C:\Users\pc\Downloads\Airbnb_Open_Data.csv\Airbnb_Open_Data.csv')
print (data.head())

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0
1  40.75362 -73.98377  United States  ...        $28            30.0
2  40.80902 -73.94190  United States  ...       $124             3.0
3  40.68514 -73.95976  United States  ...        $74            30.0
4  40.79851 -73.94399  United States  ...        $41            10.0

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0
1              45.0   5/21/2022               0.38                4.0
2               0.0         NaN                NaN                5.0
3             270.0    7/5/2019               4.64                4.0
4               9.0  11/19/2018               0.10                3.0

  calculated host listings count  availability 365  \
0                            6.0             286.0
1                            2.0             228.0
2                            1.0             352.0
3                            1.0             322.0
4                            1.0             289.0

                                         house_rules license
0  Clean up and treat the home the way you'd like...     NaN
1  Pet friendly but please confirm with me if the...     NaN
2  I encourage you to use my kitchen, cooking and...     NaN
3                                                NaN     NaN
4  Please no smoking in the house, porch or on th...     NaN

[5 rows x 26 columns]

C:\Users\pc\AppData\Local\Temp\ipykernel_2240\1813651972.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r'C:\Users\pc\Downloads\Airbnb_Open_Data.csv\Airbnb_Open_Data.csv')

In [57]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [58]:
columns_to_drop= ['id',
    'NAME',
    'host id',
    'host name',
    'country',
    'country code',
    'house_rules',
    'license',
    'last review']
columns_to_keep=['host_identity_verified',
    'neighbourhood group',
    'neighbourhood',
    'lat',
    'long',
    'instant_bookable',
    'cancellation_policy',
    'room type',
    'Construction year',
    'minimum nights',
    'number of reviews',
    'reviews per month',
    'review rate number',
    'calculated host listings count',
    'availability 365']

In [59]:
data.drop(columns = columns_to_drop, inplace=True)

In [60]:
data.columns

Index(['host_identity_verified', 'neighbourhood group', 'neighbourhood', 'lat',
       'long', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365'],
      dtype='object')

In [61]:
data

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0
1,verified,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0
2,NaN,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,5.0,1.0,352.0
3,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,4.64,4.0,1.0,322.0
4,verified,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,verified,Brooklyn,Williamsburg,40.70862,-73.94651,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,3.0,1.0,227.0
102595,unconfirmed,Manhattan,Morningside Heights,40.80460,-73.96545,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,0.02,2.0,2.0,395.0
102596,unconfirmed,Brooklyn,Park Slope,40.67505,-73.98045,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,5.0,1.0,342.0
102597,unconfirmed,Queens,Long Island City,40.74989,-73.93777,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,0.10,3.0,1.0,386.0
102598,unconfirmed,Manhattan,Upper West Side,40.76807,-73.98342,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,3.0,1.0,69.0

In [62]:
data.columns = [col.capitalize() for col in data.columns]

In [63]:
data

,Host_identity_verified,Neighbourhood group,Neighbourhood,Lat,Long,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Reviews per month,Review rate number,Calculated host listings count,Availability 365
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0
1,verified,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0
2,NaN,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,5.0,1.0,352.0
3,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,4.64,4.0,1.0,322.0
4,verified,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,verified,Brooklyn,Williamsburg,40.70862,-73.94651,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,3.0,1.0,227.0
102595,unconfirmed,Manhattan,Morningside Heights,40.80460,-73.96545,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,0.02,2.0,2.0,395.0
102596,unconfirmed,Brooklyn,Park Slope,40.67505,-73.98045,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,5.0,1.0,342.0
102597,unconfirmed,Queens,Long Island City,40.74989,-73.93777,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,0.10,3.0,1.0,386.0
102598,unconfirmed,Manhattan,Upper West Side,40.76807,-73.98342,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,3.0,1.0,69.0

In [64]:
data.duplicated().value_counts()

False    98963
True      3636
Name: count, dtype: int64

In [65]:
data.drop_duplicates(inplace=True)

In [66]:
data

,Host_identity_verified,Neighbourhood group,Neighbourhood,Lat,Long,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Reviews per month,Review rate number,Calculated host listings count,Availability 365
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0
1,verified,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0
2,NaN,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,5.0,1.0,352.0
3,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,4.64,4.0,1.0,322.0
4,verified,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,unconfirmed,Brooklyn,Flatbush,40.64945,-73.96108,True,moderate,Private room,NaN,$696,NaN,7.0,12.0,0.44,5.0,1.0,0.0
102054,verified,Brooklyn,Bushwick,40.69872,-73.92718,False,flexible,Private room,NaN,$909,NaN,1.0,19.0,0.72,3.0,2.0,0.0
102055,verified,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,True,moderate,Entire home/apt,NaN,$387,NaN,2.0,50.0,3.12,4.0,2.0,235.0
102056,unconfirmed,Manhattan,Harlem,40.81248,-73.94317,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN,1.0,1.0,0.0
102057,verified,Manhattan,Harlem,40.81315,-73.94747,False,flexible,Entire home/apt,2011.0,"$1,128",NaN,4.0,22.0,0.85,4.0,1.0,238.0

In [67]:
data.isna().sum()

Host_identity_verified              289
Neighbourhood group                  29
Neighbourhood                        16
Lat                                   8
Long                                  8
Instant_bookable                    105
Cancellation_policy                  76
Room type                             0
Construction year                   214
Price                               247
Service fee                         273
Minimum nights                      398
Number of reviews                   180
Reviews per month                 15338
Review rate number                  313
Calculated host listings count      308
Availability 365                    448
dtype: int64

In [68]:
data = data.drop(columns=['Reviews per month'])

In [69]:
data.isna().sum()

Host_identity_verified            289
Neighbourhood group                29
Neighbourhood                      16
Lat                                 8
Long                                8
Instant_bookable                  105
Cancellation_policy                76
Room type                           0
Construction year                 214
Price                             247
Service fee                       273
Minimum nights                    398
Number of reviews                 180
Review rate number                313
Calculated host listings count    308
Availability 365                  448
dtype: int64

In [70]:
data.dropna(inplace = True)

In [71]:
data.isna().sum()

Host_identity_verified            0
Neighbourhood group               0
Neighbourhood                     0
Lat                               0
Long                              0
Instant_bookable                  0
Cancellation_policy               0
Room type                         0
Construction year                 0
Price                             0
Service fee                       0
Minimum nights                    0
Number of reviews                 0
Review rate number                0
Calculated host listings count    0
Availability 365                  0
dtype: int64

In [88]:
data['Price'].str.replace('$','')

0           966
1           142
3           368
4           204
5           577
           ...
102031    1,078
102032      103
102040      982
102041      946
102043    1,043
Name: Price, Length: 96499, dtype: object

In [89]:
data['Price'].str.replace(',','')

0          $966
1          $142
3          $368
4          $204
5          $577
           ...
102031    $1078
102032     $103
102040     $982
102041     $946
102043    $1043
Name: Price, Length: 96499, dtype: object

In [90]:
data['Price']

0           $966
1           $142
3           $368
4           $204
5           $577
           ...
102031    $1,078
102032      $103
102040      $982
102041      $946
102043    $1,043
Name: Price, Length: 96499, dtype: object

In [91]:
data['Price'].str.replace('$','')
data['Price'].str.replace(',','')

0          $966
1          $142
3          $368
4          $204
5          $577
           ...
102031    $1078
102032     $103
102040     $982
102041     $946
102043    $1043
Name: Price, Length: 96499, dtype: object

In [92]:
data['Price'].str.replace('$','')

0           966
1           142
3           368
4           204
5           577
           ...
102031    1,078
102032      103
102040      982
102041      946
102043    1,043
Name: Price, Length: 96499, dtype: object

In [94]:
data

,Lat,Long,Construction year,Price,Service fee,Minimum nights,Number of reviews,Review rate number,Calculated host listings count,Availability 365,...,Neighbourhood_Windsor Terrace,Neighbourhood_Woodhaven,Neighbourhood_Woodlawn,Neighbourhood_Woodrow,Neighbourhood_Woodside,Cancellation_policy_moderate,Cancellation_policy_strict,Room type_Hotel room,Room type_Private room,Room type_Shared room
0,40.64749,-73.97237,2020.0,$966,$193,10.0,9.0,4.0,6.0,286.0,...,False,False,False,False,False,False,True,False,True,False
1,40.75362,-73.98377,2007.0,$142,$28,30.0,45.0,4.0,2.0,228.0,...,False,False,False,False,False,True,False,False,False,False
3,40.68514,-73.95976,2005.0,$368,$74,30.0,270.0,4.0,1.0,322.0,...,False,False,False,False,False,True,False,False,False,False
4,40.79851,-73.94399,2009.0,$204,$41,10.0,9.0,3.0,1.0,289.0,...,False,False,False,False,False,True,False,False,False,False
5,40.74767,-73.97500,2013.0,$577,$115,3.0,74.0,3.0,1.0,374.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102031,40.70870,-73.96710,2020.0,"$1,078",$216,1.0,58.0,5.0,2.0,120.0,...,False,False,False,False,False,False,False,False,True,False
102032,40.75047,-73.75349,2007.0,$103,$21,7.0,40.0,1.0,5.0,148.0,...,False,False,False,False,False,True,False,False,True,False
102040,40.76245,-73.87938,2022.0,$982,$196,1.0,239.0,2.0,2.0,361.0,...,False,False,False,False,False,False,True,False,True,False
102041,40.59380,-73.77373,2020.0,$946,$189,1.0,76.0,1.0,1.0,324.0,...,False,False,False,False,False,True,False,False,True,False
102043,40.72318,-74.00223,2020.0,"$1,043",$209,2.0,21.0,4.0,2.0,343.0,...,False,False,False,False,False,False,False,False,False,False

In [95]:
data.columns

Index(['Lat', 'Long', 'Construction year', 'Price', 'Service fee',
       'Minimum nights', 'Number of reviews', 'Review rate number',
       'Calculated host listings count', 'Availability 365',
       ...
       'Neighbourhood_Windsor Terrace', 'Neighbourhood_Woodhaven',
       'Neighbourhood_Woodlawn', 'Neighbourhood_Woodrow',
       'Neighbourhood_Woodside', 'Cancellation_policy_moderate',
       'Cancellation_policy_strict', 'Room type_Hotel room',
       'Room type_Private room', 'Room type_Shared room'],
      dtype='object', length=243)

In [101]:
y = data['Price']
X = data.drop(columns=['Price'])

In [102]:
X_single = data[['Service fee']]

In [103]:
X_multi = data.drop(columns=['Price'])

In [104]:
from sklearn.model_selection import train_test_split

X_train_s, X_test_s, y_train, y_test = train_test_split(X_single, y, test_size=0.2, random_state=42)
X_train_m, X_test_m, _, _ = train_test_split(X_multi, y, test_size=0.2, random_state=42)

In [106]:
data['Price'] = data['Price'].replace('[\$,]', '', regex=True).astype(float)
data['Service fee'] = data['Service fee'].replace('[\$,]', '', regex=True).astype(float)

In [107]:
y = data['Price']
X = data.drop(columns=['Price'])

In [108]:
from sklearn.model_selection import train_test_split

X_train_s, X_test_s, y_train, y_test = train_test_split(X[['Service fee']], y, test_size=0.2, random_state=42)

X_train_m, X_test_m, _, _ = train_test_split(X, y, test_size=0.2, random_state=42)

In [110]:
from sklearn.linear_model import LinearRegression

model_single = LinearRegression()
model_single.fit(X_train_s, y_train)

model_multi = LinearRegression()
model_multi.fit(X_train_m, y_train)

LinearRegression()

In [111]:
y_pred_single = model_single.predict(X_test_s)
y_pred_multi = model_multi.predict(X_test_m)

In [112]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse_single = np.sqrt(mean_squared_error(y_test, y_pred_single))
r2_single = r2_score(y_test, y_pred_single)


rmse_multi = np.sqrt(mean_squared_error(y_test, y_pred_multi))
r2_multi = r2_score(y_test, y_pred_multi)

print("Single Feature Model:")
print("RMSE:", rmse_single)
print("R²:", r2_single)

print("\nMultiple Feature Model:")
print("RMSE:", rmse_multi)
print("R²:", r2_multi)

Single Feature Model:
RMSE: 1.4153960606044438
R²: 0.9999817960896424

Multiple Feature Model:
RMSE: 1.4164891035698208
R²: 0.9999817679627602

In [113]:
print("Coefficient:", model_single.coef_)
print("Intercept:", model_single.intercept_)

Coefficient: [4.99968277]
Intercept: 0.035640902750174064

In [114]:
coefficients = pd.DataFrame(model_multi.coef_, X_multi.columns, columns=['Coefficient'])
print(coefficients)

                              Coefficient
Lat                             -0.806954
Long                             0.931639
Construction year               -0.000628
Service fee                      4.999686
Minimum nights                  -0.000263
...                                   ...
Cancellation_policy_moderate    -0.014049
Cancellation_policy_strict       0.008810
Room type_Hotel room            -0.118874
Room type_Private room           0.028879
Room type_Shared room            0.034814

[242 rows x 1 columns]

In [115]:
import joblib

joblib.dump(model_multi, 'price_prediction_model.pkl')

['price_prediction_model.pkl']

In [116]:
model = joblib.load('price_prediction_model.pkl')

example = X_test_m.iloc[0:1]

prediction = model.predict(example)
print("Predicted Price:", prediction)

Predicted Price: [564.91080439]

In [ ]:
#“The multiple linear regression model was selected as the final model because it captures more relationships between variables and provides better predictive performance.”